/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package sintaxAnalysis;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int TIMER = 15;
  /** RegularExpression Id. */
  int RANGO_TIMER = 16;
  /** RegularExpression Id. */
  int OPCIONESRANGO = 17;
  /** RegularExpression Id. */
  int DIM_FILAS = 18;
  /** RegularExpression Id. */
  int DIM_COLUMNAS = 19;
  /** RegularExpression Id. */
  int CUBO = 20;
  /** RegularExpression Id. */
  int LIST = 21;
  /** RegularExpression Id. */
  int MAIN = 22;
  /** RegularExpression Id. */
  int RANGO = 23;
  /** RegularExpression Id. */
  int NEG = 24;
  /** RegularExpression Id. */
  int T = 25;
  /** RegularExpression Id. */
  int F = 26;
  /** RegularExpression Id. */
  int INSERT = 27;
  /** RegularExpression Id. */
  int DELETE = 28;
  /** RegularExpression Id. */
  int LENGTH = 29;
  /** RegularExpression Id. */
  int SHAPEF = 38;
  /** RegularExpression Id. */
  int SHAPEC = 39;
  /** RegularExpression Id. */
  int ID = 40;
  /** RegularExpression Id. */
  int OPERADORES = 41;
  /** RegularExpression Id. */
  int OPERADOR_COMPARADOR = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "<NUM>",
    "<BOOL>",
    "\"Timer\"",
    "\"Rango_Timer\"",
    "<OPCIONESRANGO>",
    "\"Dim_Filas\"",
    "\"Dim_Columnas\"",
    "\"Cubo\"",
    "\"list\"",
    "\"Main\"",
    "\"range\"",
    "\"Neg\"",
    "\"T\"",
    "\"F\"",
    "\"insert\"",
    "\"del\"",
    "\"len\"",
    "\"if\"",
    "\"for\"",
    "\"Call\"",
    "\"Procedure\"",
    "\"Delay\"",
    "\"in\"",
    "\"Step\"",
    "\"Blink\"",
    "\"shapeF\"",
    "\"shapeC\"",
    "<ID>",
    "<OPERADORES>",
    "<OPERADOR_COMPARADOR>",
    "\";\"",
    "\"type(\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
  };

}
