/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int TIMER = 10;
  /** RegularExpression Id. */
  int RANGO_TIMER = 11;
  /** RegularExpression Id. */
  int OPCIONESRANGO = 12;
  /** RegularExpression Id. */
  int DIM_FILAS = 13;
  /** RegularExpression Id. */
  int DIM_COLUMNAS = 14;
  /** RegularExpression Id. */
  int CUBO = 15;
  /** RegularExpression Id. */
  int LIST = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int RANGO = 18;
  /** RegularExpression Id. */
  int NEG = 19;
  /** RegularExpression Id. */
  int T = 20;
  /** RegularExpression Id. */
  int F = 21;
  /** RegularExpression Id. */
  int INSERT = 22;
  /** RegularExpression Id. */
  int DELETE = 23;
  /** RegularExpression Id. */
  int LENGTH = 24;
  /** RegularExpression Id. */
  int SHAPEF = 33;
  /** RegularExpression Id. */
  int SHAPEC = 34;
  /** RegularExpression Id. */
  int ID = 35;
  /** RegularExpression Id. */
  int OPERADORES = 36;
  /** RegularExpression Id. */
  int OPERADOR_COMPARADOR = 37;
  /** RegularExpression Id. */
  int COMMENT = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "<NUM>",
    "<BOOL>",
    "\"Timer\"",
    "\"Rango_Timer\"",
    "<OPCIONESRANGO>",
    "\"Dim_Filas\"",
    "\"Dim_Columnas\"",
    "\"Cubo\"",
    "\"list\"",
    "\"Main\"",
    "\"range\"",
    "\"Neg\"",
    "\"T\"",
    "\"F\"",
    "\"insert\"",
    "\"del\"",
    "\"len\"",
    "\"if\"",
    "\"for\"",
    "\"Call\"",
    "\"Procedure\"",
    "\"Delay\"",
    "\"in\"",
    "\"Step\"",
    "\"Blink\"",
    "\"shapeF\"",
    "\"shapeC\"",
    "<ID>",
    "<OPERADORES>",
    "<OPERADOR_COMPARADOR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
  };

}
